"use client";
import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { createSupabaseBrowserClient } from "../../lib/supabase/browser";

export default function LoginPage() {
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [invited,setInvited]=useState(false);
  useEffect(()=>{const params=new URLSearchParams(window.location.hash.slice(1));const access=params.get("access_token"),refresh=params.get("refresh_token"),type=params.get("type");if(!access||!refresh||!["invite","recovery"].includes(type||""))return;void createSupabaseBrowserClient().auth.setSession({access_token:access,refresh_token:refresh}).then(({error})=>{if(error)setError(error.message);else{setInvited(true);window.history.replaceState({},"","/login");}});},[]);
  async function bootstrap(){const response=await fetch("/api/auth/bootstrap",{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Acesso não autorizado");window.location.assign("/gestao");}
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{const supabase=createSupabaseBrowserClient();const {error:authError}=await supabase.auth.signInWithPassword({email:String(data.get("email")),password:String(data.get("password"))});if(authError)throw authError;await bootstrap();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível entrar.");setBusy(false);}}
  async function definePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget),password=String(data.get("password")),confirmation=String(data.get("confirmation"));try{if(password.length<8)throw new Error("Use uma senha com pelo menos 8 caracteres.");if(password!==confirmation)throw new Error("As senhas não coincidem.");const {error:updateError}=await createSupabaseBrowserClient().auth.updateUser({password});if(updateError)throw updateError;await bootstrap();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível definir a senha.");setBusy(false);}}
  return <main className="management-login"><section><Image src="/logo-ta-no-banho.jpeg" alt="Tá no Banho" width={190} height={130} priority/><p>PAINEL DE GESTÃO</p><h1>{invited?"Defina sua senha":"Bem-vindo de volta"}</h1><span>{invited?"Crie a senha do primeiro administrador do Tá no Banho.":"Entre com a conta administrativa própria do Tá no Banho."}</span>{invited?<form onSubmit={definePassword}><label>Nova senha<input name="password" type="password" autoComplete="new-password" minLength={8} required/></label><label>Confirmar senha<input name="confirmation" type="password" autoComplete="new-password" minLength={8} required/></label>{error&&<div role="alert">{error}</div>}<button disabled={busy}>{busy?"Salvando...":"Salvar senha e entrar"}</button></form>:<form onSubmit={login}><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div role="alert">{error}</div>}<button disabled={busy}>{busy?"Entrando...":"Entrar no painel"}</button></form>}<a href="/agendar">Ir para reservas on-line</a></section></main>;
}
